### ISSUE TITLE
favicon.ico

### ISSUE THREAD

**Issue by 1684838553** [gaoac/electron-react-typescript-starter#33]
你好，想问下怎么这个项目怎么替换electron的默认图标。在public/index.html和 new BrowserWindow()中配置都不生效

**Comment by gaoac** [comment]
可能是平台的原因，可以参考下这个 https://www.electronforge.io/guides/create-and-add-icons#supported-formats
另外这个项目5年前的了，很多技术都已经进步了，建议直接使用最新版的[Electron Forge](https://www.electronforge.io/)

**Comment by 1684838553** [comment]
好的，已解决，谢谢
